### ISSUE TITLE
Sample GraphCMS Schema

### ISSUE THREAD

**Issue by slavakurilyak** [chec/headlesscommerce.org#109]
Please share a sample of the Graph CMS schema, so other developers can build upon this repo.

![screen](https://user-images.githubusercontent.com/6625584/103155226-7aea5500-4752-11eb-9300-6c9cb276eebd.jpg)

**Comment by notrab** [comment]
Hey @slavakurilyak 

I've gone ahead and updated the `.env.sample` to include the default endpoint, and public API token.

Here are the screenshots of the schema (I'll set this up on GraphCMS as a template you can clone at some point).

<img width="1092" alt="Screenshot 2021-01-07 at 20 02 35" src="https://user-images.githubusercontent.com/950181/103939173-49df2c80-5123-11eb-97a6-d32c6291a193.png">
<img width="1081" alt="Screenshot 2021-01-07 at 20 02 42" src="https://user-images.githubusercontent.com/950181/103939183-4d72b380-5123-11eb-9da1-4a190f0db093.png">
<img width="1055" alt="Screenshot 2021-01-07 at 20 02 48" src="https://user-images.githubusercontent.com/950181/103939194-51063a80-5123-11eb-9f8f-93e66088c9c1.png">
<img width="1053" alt="Screenshot 2021-01-07 at 20 02 53" src="https://user-images.githubusercontent.com/950181/103939199-5499c180-5123-11eb-809d-dce703b07a5f.png">

**Comment by slavakurilyak** [comment]
@notrab Thanks for sharing this!
