### ISSUE TITLE
Add ButterCMS! :)

### ISSUE THREAD

**Issue by jakelumetta** [chec/headlesscommerce.org#35]
Hi - I'd like to add https://buttercms.com to the list of services here.  Is the data stored in this repo or is it stored in an Algolia Index? How can I contribute? Thanks!

**Comment by ScopeyNZ** [comment]
Hey Jake. The data is actually managed in Airtable! We have a form on the site that you can use to suggest ButterCMS:

![image](https://user-images.githubusercontent.com/3260989/92148865-fefa8480-edd1-11ea-99a1-722e678dc0d1.png)

**Comment by jakelumetta** [comment]
👍

**Comment by notrab** [comment]
Hey @jakelumetta 

Thanks for the suggestion. I'll get it added now 😅

**Comment by jakelumetta** [comment]
Thanks @notrab !

**Comment by notrab** [comment]
@jakelumetta added 🧈 

It'll move up and down the list based on popularity. We're making some changes soon too that will mean you can add even more about ButterCMS to its own page 🚀

**Comment by jakelumetta** [comment]
Cool thanks. How is popularity measured?

**Comment by notrab** [comment]
@jakelumetta we're tracking clicks currently via GA Events, and then those are updated in the index, however, it's not a perfect method for all sorts of edge cases, as you can imagine. We're busy updating the site currently, which will allow users to upvote/comment/rate too, which will all play into ranking.
